#!/usr/bin/env bash

set -xe

if [[ -f /proc/cpuinfo ]]
then
    core_number=$(cat /proc/cpuinfo  | grep -c ^processor)
else
    core_number=2
fi

# this section to be made smarter in the future
# will kinda get automatically smarter once reaverlib itself uses develop and master for stable
function install_package() {
    local package=$1
    local branch=$2

    wget https://github.com/reaver-project/${package}/archive/${branch}.zip
    unzip ${branch}.zip
    cd ${package}-${branch}
    make install # no sudo needed; to be executed in docker as sudo
    cd ..
    rm -rf ${package}-${branch} ${branch}.zip
}

install_package reaverlib master
install_package mayfly develop

make -j${core_number} -l${core_number}

make test -j${core_number} -l${core_number}
./tests/test -j ${core_number} -l 3 -r teamcity

./vprc
echo '#include <stdlib.h>' >> output/output.cpp
echo 'int main(int argc, char ** argv) { return hello_world::entry(atoi(argv[1])); }' >> output/output.cpp
c++ -Wno-extra-qualification -Werror -std=c++1z -O3 output/output.cpp -o output/output -g -fsanitize=address
./output/output 3

